version: '3'
services:
  ea_nginx:
    image: nginx
    links:
      - ea_phpfpm
    volumes:
      - ./:/code
      - ./nginx.conf:/etc/nginx/conf.d/default.conf

  ea_phpfpm:
    build: docker/php
    links:
      - ea_db
    volumes:
      - ./:/code
    working_dir: /code

  ea_db:
    image: postgres
    expose:
      - 5432
